export {default as Home} from './Home'
export {default as About} from './About'
export {default as Charges} from './Charges'
export {default as Contact} from './Contact'
export {default as Navbar} from './Navbar'